# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainLayout.ui'
#
# Created: Sat Feb 16 20:04:57 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1131, 679)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/movies.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.centralFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralFrame.sizePolicy().hasHeightForWidth())
        self.centralFrame.setSizePolicy(sizePolicy)
        self.centralFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.centralFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.centralFrame.setObjectName("centralFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralFrame)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.location = QtGui.QComboBox(self.centralFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.location.sizePolicy().hasHeightForWidth())
        self.location.setSizePolicy(sizePolicy)
        self.location.setEditable(True)
        self.location.setModelColumn(0)
        self.location.setObjectName("location")
        self.horizontalLayout_3.addWidget(self.location)
        self.btnStartDl = QtGui.QPushButton(self.centralFrame)
        self.btnStartDl.setCheckable(True)
        self.btnStartDl.setFlat(False)
        self.btnStartDl.setObjectName("btnStartDl")
        self.horizontalLayout_3.addWidget(self.btnStartDl)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabPanel = QtGui.QTabWidget(self.centralFrame)
        self.tabPanel.setObjectName("tabPanel")
        self.tabBrowser = QtGui.QWidget()
        self.tabBrowser.setObjectName("tabBrowser")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/apps-display-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabPanel.addTab(self.tabBrowser, icon1, "")
        self.tabConfig = QtGui.QWidget()
        self.tabConfig.setObjectName("tabConfig")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabConfig)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameTab = QtGui.QFrame(self.tabConfig)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frameTab.sizePolicy().hasHeightForWidth())
        self.frameTab.setSizePolicy(sizePolicy)
        self.frameTab.setFrameShape(QtGui.QFrame.Panel)
        self.frameTab.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameTab.setObjectName("frameTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frameTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hSliderPageConf = QtGui.QSlider(self.frameTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hSliderPageConf.sizePolicy().hasHeightForWidth())
        self.hSliderPageConf.setSizePolicy(sizePolicy)
        self.hSliderPageConf.setMinimum(0)
        self.hSliderPageConf.setMaximum(2)
        self.hSliderPageConf.setPageStep(1)
        self.hSliderPageConf.setProperty("value", 0)
        self.hSliderPageConf.setOrientation(QtCore.Qt.Horizontal)
        self.hSliderPageConf.setTickPosition(QtGui.QSlider.TicksBelow)
        self.hSliderPageConf.setObjectName("hSliderPageConf")
        self.verticalLayout_4.addWidget(self.hSliderPageConf)
        self.groupTypes = QtGui.QToolBox(self.frameTab)
        self.groupTypes.setObjectName("groupTypes")
        self.configConnection = QtGui.QWidget()
        self.configConnection.setGeometry(QtCore.QRect(0, 0, 1028, 359))
        self.configConnection.setObjectName("configConnection")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.configConnection)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(11, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtGui.QGroupBox(self.configConnection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, -1, 11, -1)
        self.gridLayout_2.setHorizontalSpacing(30)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.connectionSpeed = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionSpeed.sizePolicy().hasHeightForWidth())
        self.connectionSpeed.setSizePolicy(sizePolicy)
        self.connectionSpeed.setMinimum(1024)
        self.connectionSpeed.setMaximum(1073741824)
        self.connectionSpeed.setProperty("value", 35840)
        self.connectionSpeed.setObjectName("connectionSpeed")
        self.gridLayout_2.addWidget(self.connectionSpeed, 1, 1, 1, 1)
        self.connectionActive = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionActive.sizePolicy().hasHeightForWidth())
        self.connectionActive.setSizePolicy(sizePolicy)
        self.connectionActive.setAutoFillBackground(False)
        self.connectionActive.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.connectionActive.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.connectionActive.setMinimum(1)
        self.connectionActive.setMaximum(30)
        self.connectionActive.setProperty("value", 1)
        self.connectionActive.setObjectName("connectionActive")
        self.gridLayout_2.addWidget(self.connectionActive, 0, 1, 1, 1)
        self.connectionTimeout = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionTimeout.sizePolicy().hasHeightForWidth())
        self.connectionTimeout.setSizePolicy(sizePolicy)
        self.connectionTimeout.setMinimum(1)
        self.connectionTimeout.setMaximum(300)
        self.connectionTimeout.setProperty("value", 60)
        self.connectionTimeout.setObjectName("connectionTimeout")
        self.gridLayout_2.addWidget(self.connectionTimeout, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.configConnection)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setHorizontalSpacing(30)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 24, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.connectionSleep = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectionSleep.sizePolicy().hasHeightForWidth())
        self.connectionSleep.setSizePolicy(sizePolicy)
        self.connectionSleep.setMinimum(1)
        self.connectionSleep.setMaximum(300)
        self.connectionSleep.setProperty("value", 2)
        self.connectionSleep.setObjectName("connectionSleep")
        self.gridLayout_3.addWidget(self.connectionSleep, 0, 1, 1, 1)
        self.connectionAttempts = QtGui.QSpinBox(self.groupBox_2)
        self.connectionAttempts.setMinimum(1)
        self.connectionAttempts.setMaximum(30)
        self.connectionAttempts.setObjectName("connectionAttempts")
        self.gridLayout_3.addWidget(self.connectionAttempts, 24, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(self.configConnection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.connectionType = QtGui.QCheckBox(self.groupBox_4)
        self.connectionType.setChecked(True)
        self.connectionType.setObjectName("connectionType")
        self.verticalLayout_12.addWidget(self.connectionType)
        self.proxyDisable = QtGui.QCheckBox(self.groupBox_4)
        self.proxyDisable.setChecked(True)
        self.proxyDisable.setObjectName("proxyDisable")
        self.verticalLayout_12.addWidget(self.proxyDisable)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/network-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.groupTypes.addItem(self.configConnection, icon2, "")
        self.configMovie = QtGui.QWidget()
        self.configMovie.setGeometry(QtCore.QRect(0, 0, 1049, 346))
        self.configMovie.setObjectName("configMovie")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.configMovie)
        self.verticalLayout_9.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnToolDir = QtGui.QToolButton(self.configMovie)
        self.btnToolDir.setCheckable(False)
        self.btnToolDir.setObjectName("btnToolDir")
        self.gridLayout_6.addWidget(self.btnToolDir, 1, 1, 1, 1)
        self.videoDir = QtGui.QLineEdit(self.configMovie)
        self.videoDir.setReadOnly(True)
        self.videoDir.setObjectName("videoDir")
        self.gridLayout_6.addWidget(self.videoDir, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.configMovie)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.configMovie)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.videoQuality = QtGui.QComboBox(self.configMovie)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoQuality.sizePolicy().hasHeightForWidth())
        self.videoQuality.setSizePolicy(sizePolicy)
        self.videoQuality.setToolTip("")
        self.videoQuality.setDuplicatesEnabled(False)
        self.videoQuality.setObjectName("videoQuality")
        self.gridLayout_6.addWidget(self.videoQuality, 0, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_6)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/movies-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.groupTypes.addItem(self.configMovie, icon3, "")
        self.configFile = QtGui.QWidget()
        self.configFile.setGeometry(QtCore.QRect(0, 0, 1049, 346))
        self.configFile.setObjectName("configFile")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.configFile)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtGui.QLabel(self.configFile)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 8, 0, 1, 1)
        self.tempFileAction = QtGui.QComboBox(self.configFile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempFileAction.sizePolicy().hasHeightForWidth())
        self.tempFileAction.setSizePolicy(sizePolicy)
        self.tempFileAction.setObjectName("tempFileAction")
        self.gridLayout_4.addWidget(self.tempFileAction, 0, 1, 1, 1)
        self.videoSplitSize = QtGui.QSpinBox(self.configFile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoSplitSize.sizePolicy().hasHeightForWidth())
        self.videoSplitSize.setSizePolicy(sizePolicy)
        self.videoSplitSize.setMinimum(1)
        self.videoSplitSize.setMaximum(5)
        self.videoSplitSize.setProperty("value", 4)
        self.videoSplitSize.setObjectName("videoSplitSize")
        self.gridLayout_4.addWidget(self.videoSplitSize, 8, 1, 1, 1)
        self.tempFiles = QtGui.QCheckBox(self.configFile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempFiles.sizePolicy().hasHeightForWidth())
        self.tempFiles.setSizePolicy(sizePolicy)
        self.tempFiles.setChecked(True)
        self.tempFiles.setObjectName("tempFiles")
        self.gridLayout_4.addWidget(self.tempFiles, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/files-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.groupTypes.addItem(self.configFile, icon4, "")
        self.verticalLayout_4.addWidget(self.groupTypes)
        self.verticalLayout_3.addWidget(self.frameTab)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/settings-tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabPanel.addTab(self.tabConfig, icon5, "")
        self.tabInfo = QtGui.QWidget()
        self.tabInfo.setObjectName("tabInfo")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabInfo)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.connectionInfo = QtGui.QTableWidget(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.connectionInfo.sizePolicy().hasHeightForWidth())
        self.connectionInfo.setSizePolicy(sizePolicy)
        self.connectionInfo.setObjectName("connectionInfo")
        self.connectionInfo.setColumnCount(9)
        self.connectionInfo.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.connectionInfo.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.connectionInfo.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.connectionInfo.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.connectionInfo.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.connectionInfo.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.connectionInfo.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.connectionInfo.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.connectionInfo.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.connectionInfo.setHorizontalHeaderItem(8, item)
        self.verticalLayout_7.addWidget(self.connectionInfo)
        self.frame = QtGui.QFrame(self.tabInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.videoExtInfo = QtGui.QLineEdit(self.groupBox_3)
        self.videoExtInfo.setReadOnly(True)
        self.videoExtInfo.setObjectName("videoExtInfo")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.videoExtInfo)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.videoSizeInfo = QtGui.QLineEdit(self.groupBox_3)
        self.videoSizeInfo.setReadOnly(True)
        self.videoSizeInfo.setObjectName("videoSizeInfo")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.videoSizeInfo)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_12)
        self.progressBarInfo = QtGui.QProgressBar(self.groupBox_3)
        self.progressBarInfo.setProperty("value", 0)
        self.progressBarInfo.setObjectName("progressBarInfo")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.progressBarInfo)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.downloadedFromInfo = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadedFromInfo.sizePolicy().hasHeightForWidth())
        self.downloadedFromInfo.setSizePolicy(sizePolicy)
        self.downloadedFromInfo.setReadOnly(True)
        self.downloadedFromInfo.setObjectName("downloadedFromInfo")
        self.horizontalLayout_5.addWidget(self.downloadedFromInfo)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.downloadedToInfo = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadedToInfo.sizePolicy().hasHeightForWidth())
        self.downloadedToInfo.setSizePolicy(sizePolicy)
        self.downloadedToInfo.setReadOnly(True)
        self.downloadedToInfo.setObjectName("downloadedToInfo")
        self.horizontalLayout_5.addWidget(self.downloadedToInfo)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_15)
        self.globalSpeedInfo = QtGui.QLineEdit(self.groupBox_3)
        self.globalSpeedInfo.setReadOnly(True)
        self.globalSpeedInfo.setObjectName("globalSpeedInfo")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.globalSpeedInfo)
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_16)
        self.globalEtaInfo = QtGui.QLineEdit(self.groupBox_3)
        self.globalEtaInfo.setReadOnly(True)
        self.globalEtaInfo.setObjectName("globalEtaInfo")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.globalEtaInfo)
        self.videoTileInfo = QtGui.QLineEdit(self.groupBox_3)
        self.videoTileInfo.setReadOnly(True)
        self.videoTileInfo.setObjectName("videoTileInfo")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.videoTileInfo)
        self.verticalLayout_10.addLayout(self.formLayout)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.verticalLayout_7.addWidget(self.frame)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../images/info-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabPanel.addTab(self.tabInfo, icon6, "")
        self.tabFiles = QtGui.QWidget()
        self.tabFiles.setObjectName("tabFiles")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tabFiles)
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.refreshFiles = QtGui.QPushButton(self.tabFiles)
        self.refreshFiles.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../images/btnrefresh-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshFiles.setIcon(icon7)
        self.refreshFiles.setIconSize(QtCore.QSize(16, 16))
        self.refreshFiles.setObjectName("refreshFiles")
        self.horizontalLayout_6.addWidget(self.refreshFiles)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.videosView = QtGui.QTreeWidget(self.tabFiles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.videosView.sizePolicy().hasHeightForWidth())
        self.videosView.setSizePolicy(sizePolicy)
        self.videosView.setObjectName("videosView")
        self.videosView.headerItem().setText(0, "1")
        self.verticalLayout_11.addWidget(self.videosView)
        self.tabPanel.addTab(self.tabFiles, icon2, "")
        self.verticalLayout.addWidget(self.tabPanel)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.centralFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1131, 26))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuEdit.setFont(font)
        self.menuEdit.setObjectName("menuEdit")
        self.menuLang = QtGui.QMenu(self.menubar)
        self.menuLang.setObjectName("menuLang")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuUpdate = QtGui.QMenu(self.menuAbout)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.menuUpdate.setFont(font)
        self.menuUpdate.setObjectName("menuUpdate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setCheckable(False)
        self.actionExit.setChecked(False)
        self.actionExit.setObjectName("actionExit")
        self.actionEnglish = QtGui.QAction(MainWindow)
        self.actionEnglish.setCheckable(True)
        self.actionEnglish.setChecked(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionEnglish.setFont(font)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionPortuguse = QtGui.QAction(MainWindow)
        self.actionPortuguse.setCheckable(True)
        self.actionPortuguse.setChecked(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionPortuguse.setFont(font)
        self.actionPortuguse.setObjectName("actionPortuguse")
        self.actionAbout = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSpanish = QtGui.QAction(MainWindow)
        self.actionSpanish.setCheckable(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionSpanish.setFont(font)
        self.actionSpanish.setObjectName("actionSpanish")
        self.actionReloadPlayer = QtGui.QAction(MainWindow)
        self.actionReloadPlayer.setCheckable(False)
        self.actionReloadPlayer.setIcon(icon7)
        self.actionReloadPlayer.setObjectName("actionReloadPlayer")
        self.actionChooseExternalPlayer = QtGui.QAction(MainWindow)
        self.actionChooseExternalPlayer.setCheckable(False)
        self.actionChooseExternalPlayer.setObjectName("actionChooseExternalPlayer")
        self.actionEmbedPlayer = QtGui.QAction(MainWindow)
        self.actionEmbedPlayer.setCheckable(True)
        self.actionEmbedPlayer.setChecked(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionEmbedPlayer.setFont(font)
        self.actionEmbedPlayer.setObjectName("actionEmbedPlayer")
        self.actionExternalPlayer = QtGui.QAction(MainWindow)
        self.actionExternalPlayer.setCheckable(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionExternalPlayer.setFont(font)
        self.actionExternalPlayer.setObjectName("actionExternalPlayer")
        self.actionErroReporting = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.actionErroReporting.setFont(font)
        self.actionErroReporting.setObjectName("actionErroReporting")
        self.actionAutomaticSearch = QtGui.QAction(MainWindow)
        self.actionAutomaticSearch.setCheckable(True)
        self.actionAutomaticSearch.setChecked(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionAutomaticSearch.setFont(font)
        self.actionAutomaticSearch.setObjectName("actionAutomaticSearch")
        self.actionCheckNow = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionCheckNow.setFont(font)
        self.actionCheckNow.setObjectName("actionCheckNow")
        self.menuEdit.addAction(self.actionEmbedPlayer)
        self.menuEdit.addAction(self.actionExternalPlayer)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionChooseExternalPlayer)
        self.menuEdit.addAction(self.actionReloadPlayer)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionExit)
        self.menuLang.addAction(self.actionEnglish)
        self.menuLang.addAction(self.actionPortuguse)
        self.menuLang.addAction(self.actionSpanish)
        self.menuUpdate.addAction(self.actionAutomaticSearch)
        self.menuUpdate.addAction(self.actionCheckNow)
        self.menuAbout.addAction(self.actionErroReporting)
        self.menuAbout.addAction(self.menuUpdate.menuAction())
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuLang.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabPanel.setCurrentIndex(1)
        self.groupTypes.setCurrentIndex(0)
        self.videoQuality.setCurrentIndex(-1)
        QtCore.QObject.connect(self.hSliderPageConf, QtCore.SIGNAL("valueChanged(int)"), self.groupTypes.setCurrentIndex)
        QtCore.QObject.connect(self.groupTypes, QtCore.SIGNAL("currentChanged(int)"), self.hSliderPageConf.setValue)
        QtCore.QObject.connect(self.tempFiles, QtCore.SIGNAL("toggled(bool)"), self.tempFileAction.setEnabled)
        QtCore.QObject.connect(self.btnStartDl, QtCore.SIGNAL("toggled(bool)"), self.tempFiles.setDisabled)
        QtCore.QObject.connect(self.btnStartDl, QtCore.SIGNAL("toggled(bool)"), self.videoSplitSize.setDisabled)
        QtCore.QObject.connect(self.btnStartDl, QtCore.SIGNAL("toggled(bool)"), self.videoQuality.setDisabled)
        QtCore.QObject.connect(self.btnStartDl, QtCore.SIGNAL("toggled(bool)"), self.btnToolDir.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BaixeAssista", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStartDl.setText(QtGui.QApplication.translate("MainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPanel.setTabText(self.tabPanel.indexOf(self.tabBrowser), QtGui.QApplication.translate("MainWindow", "Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Active connections", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Timeout", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Behavior", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Connection attempts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Wait between connection attempts", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Types", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionType.setText(QtGui.QApplication.translate("MainWindow", "Modify connection type", None, QtGui.QApplication.UnicodeUTF8))
        self.proxyDisable.setText(QtGui.QApplication.translate("MainWindow", "Disable proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTypes.setItemText(self.groupTypes.indexOf(self.configConnection), QtGui.QApplication.translate("MainWindow", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.btnToolDir.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Directory videos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Video quality", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTypes.setItemText(self.groupTypes.indexOf(self.configMovie), QtGui.QApplication.translate("MainWindow", "Movies", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Divide the number of times", None, QtGui.QApplication.UnicodeUTF8))
        self.tempFiles.setText(QtGui.QApplication.translate("MainWindow", "Use temporary file", None, QtGui.QApplication.UnicodeUTF8))
        self.groupTypes.setItemText(self.groupTypes.indexOf(self.configFile), QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPanel.setTabText(self.tabPanel.indexOf(self.tabConfig), QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionInfo.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Proxy", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionInfo.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Try", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionInfo.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionInfo.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Segment", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionInfo.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Downloaded", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionInfo.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionInfo.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Remainder", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionInfo.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Percent", None, QtGui.QApplication.UnicodeUTF8))
        self.connectionInfo.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "About current video download", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Video title", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Video ext", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Video size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Global progress", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Downloaded", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Global speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Eta", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPanel.setTabText(self.tabPanel.indexOf(self.tabInfo), QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabPanel.setTabText(self.tabPanel.indexOf(self.tabFiles), QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Players", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLang.setTitle(QtGui.QApplication.translate("MainWindow", "Lang", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuUpdate.setTitle(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnglish.setText(QtGui.QApplication.translate("MainWindow", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPortuguse.setText(QtGui.QApplication.translate("MainWindow", "Portuguese", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpanish.setText(QtGui.QApplication.translate("MainWindow", "Spanish", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReloadPlayer.setText(QtGui.QApplication.translate("MainWindow", "Reload player", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChooseExternalPlayer.setText(QtGui.QApplication.translate("MainWindow", "Choose external player", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEmbedPlayer.setText(QtGui.QApplication.translate("MainWindow", "Use embedded player", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExternalPlayer.setText(QtGui.QApplication.translate("MainWindow", "Use external player", None, QtGui.QApplication.UnicodeUTF8))
        self.actionErroReporting.setText(QtGui.QApplication.translate("MainWindow", "Error reporting", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutomaticSearch.setText(QtGui.QApplication.translate("MainWindow", "Automatic search", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCheckNow.setText(QtGui.QApplication.translate("MainWindow", "Check now", None, QtGui.QApplication.UnicodeUTF8))

